### ISSUE TITLE
NullReferenceException in switch on line 155

### ISSUE THREAD

**Issue by FredrikAugust** [Tijndagamer/Ludum-Dare-Text-Based-Game#4]
When I run this program in MonoDevelop on my Macbook Air I get an error saying that the variable choice is not set, and therefor leaving a `NullReferenceException`. This can be fixed by wrapping the switch in a `try` statement that catches `NullReferenceException`s.

**Comment by m-rtijn** [comment]
Random Fighter is currently a windows-only game, if you want to have OS X support using MonoDevelop feel free to fork the repo, add support and create a pull request.

**Comment by FredrikAugust** [comment]
Might do that, seems to be some issues with how it interacts with the Console object though, and I don't think I have enough skills to edit that.
