### ISSUE TITLE
Rename Event() method in Program.cs to avoid confusion

### ISSUE THREAD

**Issue by FredrikAugust** [Tijndagamer/Ludum-Dare-Text-Based-Game#5]
You should rename your `Event()` method in Program.cs to something else (perhaps `CreateEvent()`) to avoid confusion with the `Event` class in Event.cs.

**Comment by m-rtijn** [comment]
Thanks for the heads up, fixed in commit 151adea0add3a732ffb8fa97de1a5f19cb0e7b3a
